(function(){
'use strict';
const F=window.PSFood;
const esc=x=>String(x==null?'':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host,ctx,ui={tab:'overview',date:F.today(),slot:new Date().getHours()<10?0:new Date().getHours()<16?1:2,query:'',editor:null,recipeDraft:{},stockDraft:{},leftoverDraft:{},random:null,busy:false,message:'',confirm:null,stockFilter:'all',purchaseDrafts:{},recipeView:null};
try{const old=JSON.parse(localStorage.getItem('psfocus_food_ui')||'null');if(old&&['overview','recipes','stock','plan','shop'].includes(old.tab))ui.tab=old.tab;}catch(_){}
try{const cached=JSON.parse(sessionStorage.getItem('psfocus_food_reload_draft')||'null');if(cached&&['overview','recipes','stock','plan','shop'].includes(cached.tab)){ui={...ui,...cached,busy:false,confirm:null};sessionStorage.removeItem('psfocus_food_reload_draft');}}catch(_){}
const state=()=>ctx.getState();
const btn=(label,act,attrs='',primary=false)=>'<button type="button" class="food-btn'+(primary?' food-primary':'')+'" data-food-action="'+act+'" '+attrs+'>'+label+'</button>';
const field=(label,name,value='',type='text',extra='')=>'<label class="food-field">'+label+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+extra+'></label>';
const txt=(label,name,value='',placeholder='')=>'<label class="food-field">'+label+'<textarea name="'+name+'" placeholder="'+esc(placeholder)+'">'+esc(value)+'</textarea></label>';
const empty=text=>'<p class="food-empty">'+text+'</p>';
const kcal=n=>n==null?'热量待补充':F.round(n)+' kcal';
const selected=()=>F.meals(state()).find(m=>m.date===ui.date&&m.slot===ui.slot);
const startOfWeek=d=>{const n=new Date(d+'T12:00:00').getDay();return F.addDays(d,-((n+6)%7));};
function notify(message,error=false){ui.message=message;const el=host?.querySelector('.food-status');if(el){el.textContent=message;el.setAttribute('role',error?'alert':'status');}}
function commit(fn,message){fn(state());ctx.save();ui.message=message;render();}
function header(title,action=''){return '<div class="food-heading"><h2>'+title+'</h2>'+action+'</div>';}
function exp(l){return '<span class="food-expiry '+(l.expires&&l.expires<=F.addDays(F.today(),2)?'food-urgent':'')+'">'+esc(F.expiryLabel(l.expires))+'</span>';}
function summaryStock(){const lots=F.stock(state()),live=lots.filter(l=>!l.expires||l.expires>=F.today());return '<section class="food-panel food-fridge">'+header('冰箱存货',btn('全部库存','tab','data-tab="stock"'))+(lots.length?lots.slice(0,6).map(l=>'<div class="food-stock-row"><div>'+esc(l.name)+'<small>'+esc(l.location)+' · '+l.remaining+esc(l.unit)+(l.kind==='cooked'?' · 熟食':F.category(l)==='seasoning'?' · 调味品':'')+'</small></div>'+exp(l)+'</div>').join(''):empty('还没有库存，记录买回来的食材后就能自动算缺料。'))+'<div class="food-row food-foot">'+btn('记录买菜','stock-new')+'<small>'+live.length+' 批可用</small></div></section>';}
function caloriePanel(){const n=F.nutrition(state(),ui.date);return '<section class="food-panel food-calories">'+header(ui.date===F.today()?'今日摄入':'当日摄入')+'<div class="food-calorie-values"><div><small>已摄入 · 估算</small><strong>'+n.actual.kcal+' <small>kcal</small></strong>'+(n.actual.unknown?'<small>另 '+n.actual.unknown+' 餐热量待补</small>':'')+'</div><div><small>当日计划 · 估算</small><strong>'+n.planned.kcal+' <small>kcal</small></strong>'+(n.planned.unknown?'<small>另 '+n.planned.unknown+' 餐热量待补</small>':'')+'</div></div><small>按实际吃掉的比例计算；未填写热量的菜不会当作 0 kcal。</small></section>';}
function overview(){ui.date=F.today();const lots=F.stock(state()),soon=lots.filter(l=>l.expires&&l.expires<=F.addDays(F.today(),3)),n=F.nutrition(state(),ui.date),m=selected();return '<div class="food-heading food-page-heading"><div><small class="food-eyebrow">'+ui.date.replace(/-/g,'.')+'</small><h1>今天，好好吃饭</h1></div>'+btn('＋ 入库','stock-new','',true)+'</div><div class="food-glance"><div><small>已摄入 · kcal</small><strong>'+n.actual.kcal+'</strong></div><button type="button" data-food-action="tab" data-tab="stock"><small>现有库存</small><strong>'+lots.length+' <em>批</em></strong></button><button type="button" data-food-action="stock-soon"><small>优先处理</small><strong>'+soon.length+' <em>批</em></strong></button></div><div class="food-overview"><section class="food-panel food-today">'+header('当日菜谱',btn('排餐','tab','data-tab="plan"'))+'<div class="food-three">'+F.SLOTS.map((name,slot)=>{const meal=F.meals(state()).find(x=>x.date===ui.date&&x.slot===slot);return btn('<small>'+name+' · '+(meal?.finishedAt?'已吃':meal?.cookedAt?'已做好':meal?'待吃':'未安排')+'</small><span>'+esc(meal?.snapshot.name||'添加这一餐')+'</span><small>'+(meal?kcal(meal.snapshot.kcal==null?null:meal.snapshot.kcal*meal.scale):'从菜谱或剩菜选择')+'</small>','meal-select','data-slot="'+slot+'" aria-pressed="'+(ui.slot===slot)+'"');}).join('')+'</div><details class="food-today-details" '+(ui.mealExpanded||!host.classList.contains('food-mobile')?'open':'')+'><summary><span>'+F.SLOTS[ui.slot]+'详情'+(m?' · '+esc(m.snapshot.name):'')+'</span><small>做法 / 用餐记录</small></summary>'+mealDetail(m)+'</details></section>'+summaryStock()+caloriePanel()+shopPanel(true)+'</div>';}
function mealDetail(m){if(!m)return empty('这餐还没安排。')+btn('从已有菜谱或剩菜选','choose','',true);const miss=F.projection(state()).byMeal[m.id];return '<div class="food-meal-detail"><div class="food-heading"><h3>'+esc(m.snapshot.name)+'</h3><small>'+F.SLOTS[m.slot]+'</small></div>'+(m.sourceLotId?'<p class="food-muted">吃现成剩菜，不再扣原材料。</p>':'<details class="food-scale"><summary>调整这次用量 · '+m.scale+' 倍</summary><label>按菜谱做 <select data-food-change="scale" '+(m.cookedAt?'disabled':'')+'>'+[.25,.5,1,1.5,2].map(n=>'<option '+(m.scale===n?'selected':'')+' value="'+n+'">'+n+' 倍</option>').join('')+'</select></label></details>')+'<details class="food-recipe-steps" '+(!host.classList.contains('food-mobile')?'open':'')+'><summary>材料与具体做法</summary>'+ingredientGroups(F.requirements(m))+'<ol>'+m.snapshot.steps.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol></details>'+
(m.finishedAt?'<div class="food-completion"><span class="food-badge">吃了 '+Math.round(m.eatenFraction*100)+'% · '+kcal(m.snapshot.kcal==null?null:m.snapshot.kcal*m.scale*m.eatenFraction)+'</span>'+(m.eatenFraction<1?'<p>剩下的已留在熟食库存。</p>':'')+btn('撤销这次记录','undo-meal','data-id="'+esc(m.id)+'"')+'</div>':'<div class="food-completion">'+(miss?.missing.length?'<p class="food-warning">缺料：'+miss.missing.map(i=>esc(i.name)+' '+i.quantity+esc(i.unit)).join('、')+'</p>':'')+(miss?.unknown.length&&!m.cookedAt?'<label class="food-check"><input type="checkbox" id="food-confirm-unknown">适量或未换算的材料已自行确认备齐（不会精确扣减）</label>':'')+'<div class="food-row">'+(!m.cookedAt&&!m.sourceLotId?btn('已做好','cook','data-id="'+esc(m.id)+'"'):'')+btn('吃完了','finish','data-left="0" data-id="'+esc(m.id)+'"',true)+btn('有剩下','leftover','data-id="'+esc(m.id)+'"')+'</div>'+(ui.editor==='leftover'?'<form data-food-form="leftover" class="food-inline"><h3>这次还剩多少？</h3><div class="food-row">'+[['0.5','剩一半'],['0.333333','剩三分之一'],['0.25','剩四分之一']].map(([n,t])=>btn(t,'left-choice','data-left="'+n+'"')).join('')+'</div>'+field('剩余百分比','left',ui.leftoverDraft?.left||50,'number','min="1" max="99" step="1"')+(!m.sourceLotId?lifeForm(ui.leftoverDraft,true):'<small>沿用原熟食批次的期限。</small>')+'<button class="food-btn food-primary" type="submit">记下已吃的，剩余放回冰箱</button></form>':'')+'</div>')+'<div class="food-row food-foot">'+(!m.cookedAt?btn('换一道','choose'):'')+btn('在日历中查看','calendar','data-date="'+m.date+'"')+'</div></div>';}
function ingredientGroups(items){return ['ingredient','seasoning'].map(cat=>{const rows=items.filter(i=>F.category(i)===cat);return rows.length?'<div class="food-ingredient-group"><small>'+(cat==='seasoning'?'调味品':'主食材')+'</small><div class="food-ingredients">'+rows.map(i=>'<span>'+esc(i.name)+' <b>'+(i.quantity==null?'适量／待核对':i.quantity+esc(i.unit))+'</b></span>').join('')+'</div></div>':'';}).join('');}
function recipeItems(){const d=ui.recipeDraft;return F.classify(typeof d.ingredients==='string'?F.ingredients(d.ingredients):d.ingredients||[],d.categories||{});}
function classificationPreview(){const items=recipeItems();return items.length?'<small>已初步分类 · 点击标签可切换主食材 / 调味品</small><div class="food-category-chips">'+items.map(i=>btn(esc(i.name)+' <small>'+(F.category(i)==='seasoning'?'调味品':'主食材')+'</small>','ingredient-category','data-name="'+esc(F.nameKey(i.name))+'" aria-label="'+esc(i.name)+'：'+(F.category(i)==='seasoning'?'调味品':'主食材')+'，点击切换"')).join('')+'</div>':'<small>盐、酱油、食用油等自动归到调味品；可逐项调整。</small>';}
function recipeForm(){const d=ui.recipeDraft;return '<section class="food-panel food-editor-pane">'+header(d.id?'编辑菜谱':'记录菜谱','<div class="food-row">'+(d.id?btn('另记新菜','recipe-new'):'')+btn('返回菜谱','close-editor','data-mobile-only')+'</div>')+'<form data-food-form="recipe" class="food-form">'+field('菜名','name',d.name||'','text','required maxlength="120"')+'<div class="food-form-pair food-recipe-pair">'+txt('食材与用量 · 每行一样','ingredients',typeof d.ingredients==='string'?d.ingredients:(d.ingredients||[]).map(i=>i.name+' '+(i.quantity==null?'适量':i.quantity+i.unit)).join('\n'),'番茄300g\n鸡蛋2个\n盐2g\n生抽10ml')+txt('做法 · 每行一步','steps',Array.isArray(d.steps)?d.steps.join('\n'):d.steps||'','切配食材\n按顺序烹饪')+'</div><div class="food-classification">'+classificationPreview()+'</div><div class="food-form-pair">'+field('整道菜热量 kcal · 可选','kcal',d.kcal??'','number','min="0" step="any"')+'<label class="food-field">适合哪餐<select name="mealType"><option value="all">不限餐次</option>'+F.SLOTS.map((n,i)=>'<option value="'+i+'" '+(String(d.mealType)===String(i)?'selected':'')+'>'+n+'</option>').join('')+'</select></label></div>'+field('热量来源 / 备注 · 可选','nutritionSource',d.nutritionSource||'')+'<div class="food-row"><button type="submit" class="food-btn food-primary">'+(d.id?'保存修改':'保存菜谱')+'</button><small>保存后可接着记下一道。</small></div><details class="food-import" '+(ui.busy||d.sourceText||d.sourceUrl?'open':'')+'><summary>从图片、文字或分享链接导入</summary>'+field('分享链接','sourceUrl',d.sourceUrl||'')+'<div class="food-row">'+btn(ui.busy?'读取中…':'读取链接','read-link',ui.busy?'disabled':'')+'<label class="food-btn">图片识别<input type="file" accept="image/*" data-food-image hidden '+(ui.busy?'disabled':'')+'></label></div>'+txt('原文 / 识别结果','sourceText',d.sourceText||'','第一行菜名，然后材料，最后“步骤”与做法')+btn('整理到上方表格','parse-text')+'</details></form></section>';}
function recipeList(chooser=false){const qs=ui.query.trim().split(/[\s,，]+/).filter(Boolean).map(F.nameKey),recipes=F.list(state(),'recipe').filter(r=>qs.every(q=>F.nameKey(r.name+' '+r.ingredients.map(i=>i.name).join(' ')).includes(q)));return '<div class="food-heading food-page-heading"><div><h1>'+(chooser?'为这餐选一道':'我的菜谱')+'</h1><small>'+(chooser?ui.date+' · '+F.SLOTS[ui.slot]:F.list(state(),'recipe').length+' 道私藏菜谱')+'</small></div>'+btn('＋ 记菜谱','recipe-new','',true)+'</div>'+(chooser?'<section class="food-panel food-margin">'+header('先吃现成的剩菜')+(F.stock(state()).filter(l=>l.kind==='cooked'&&(!l.expires||l.expires>=ui.date)).map(l=>btn(esc(l.name)+' · '+l.remaining+esc(l.unit),'choose-left','data-id="'+esc(l.id)+'"')).join('')||'<small>暂时没有可用剩菜</small>')+'</section>':'')+'<label class="food-search"><span class="food-sr-only">搜索菜名或原材料</span><input id="food-search" value="'+esc(ui.query)+'" placeholder="搜索菜名、食材，如 番茄 鸡蛋"></label><div class="food-recipe-list">'+(recipes.length?recipes.map(r=>'<article class="food-panel food-recipe-card"><button type="button" class="food-recipe-link" data-food-action="recipe-view" data-id="'+esc(r.id)+'"><span class="food-recipe-symbol" aria-hidden="true">'+foodIcon('recipe')+'</span><span><strong>'+esc(r.name)+'</strong><small>'+kcal(r.kcal)+' · '+r.steps.length+' 步</small></span><span class="food-chevron" aria-hidden="true">›</span></button><p>'+r.ingredients.filter(i=>F.category(i)!=='seasoning').slice(0,4).map(i=>esc(i.name)).join(' · ')+'</p><div class="food-card-foot"><small>'+r.ingredients.length+' 种用料</small>'+btn(chooser?'安排这道':'安排到一餐','choose-recipe','data-id="'+esc(r.id)+'"')+'</div></article>').join(''):empty('还没有匹配菜谱。点“记菜谱”手写或导入第一道。'))+'</div>';}
function recipesPage(){if(ui.recipeView)return recipeDetails();return '<div class="food-workspace food-recipes-workspace '+(ui.editor==='recipe'?'food-editing':'')+'">'+recipeForm()+'<section class="food-browser-pane">'+recipeList()+'</section></div>';}
function stockForm(){const d=ui.stockDraft,type=d.stockClass||(d.id?(d.kind==='cooked'?'cooked':F.category(d)):'auto');return '<section class="food-panel food-editor-pane">'+header(d.id?'编辑这批库存':'记录入库',btn('返回库存','close-editor','data-mobile-only'))+'<form data-food-form="stock" class="food-form"><h3 class="food-form-section">食物信息</h3>'+field('名称','name',d.name||'','text','placeholder="例如：鸡蛋、生抽"')+'<div class="food-form-pair">'+field('现有数量','quantity',d.remaining??d.quantity??'','number','min="0" step="any" inputmode="decimal"')+field('单位','unit',d.unit||'g','text',d.id?'readonly':'')+'</div><div class="food-form-pair"><label class="food-field">分类<select name="stockClass">'+[['auto','自动识别'],['ingredient','原材料'],['seasoning','调味品'],['cooked','熟食 / 剩菜']].filter(([v])=>!d.id||((d.kind==='cooked')===(v==='cooked'))).map(([v,n])=>'<option value="'+v+'" '+(type===v?'selected':'')+'>'+n+'</option>').join('')+'</select></label>'+field('储存位置','location',d.location||'','text','placeholder="如 冷藏 / 常温"')+'</div>'+lifeForm(d,type==='cooked')+(!d.id?'<details class="food-stock-extra"><summary>批量入库 / 熟食热量</summary>'+txt('每行一样，日期与保质期应用到整批','batch',d.batch||'','番茄500g\n生抽500ml\n盐200g')+field('这批熟食总热量 kcal · 可选','kcal',d.kcal??'','number','min="0" step="any"')+'</details>':'')+'<div class="food-form-actions"><button type="submit" class="food-btn food-primary">'+(d.id?'保存修改':'确认入库')+'</button>'+(d.id?btn('记一批新的','stock-new'):'<small>按批次记录，自动计算剩余天数</small>')+'</div></form></section>';}
function stockPage(){const all=F.stock(state()),matches=(l,cat)=>cat==='soon'?l.expires&&l.expires<=F.addDays(F.today(),3):cat==='cooked'?l.kind==='cooked':cat==='seasoning'||cat==='ingredient'?l.kind!=='cooked'&&F.category(l)===cat:true,lots=all.filter(l=>matches(l,ui.stockFilter)),count=cat=>all.filter(l=>matches(l,cat)).length;return '<div class="food-workspace food-stock-workspace '+(ui.editor==='stock'?'food-editing':'')+'">'+stockForm()+'<section class="food-browser-pane"><div class="food-heading food-page-heading"><div><h1>食物库存</h1><small>'+all.length+' 批库存 · 临期优先显示</small></div>'+btn('＋ 入库','stock-new','',true)+'</div>'+(count('soon')?'<button type="button" class="food-stock-alert" data-food-action="stock-filter" data-filter="soon"><span>'+count('soon')+' 批食物需要留意</span><small>临期 / 过期　›</small></button>':'')+'<div class="food-stock-filters">'+[['all','全部'],['ingredient','原材料'],['seasoning','调味品'],['cooked','熟食'],['soon','临期']].map(([v,n])=>btn(n+' <small>'+count(v)+'</small>','stock-filter','data-filter="'+v+'" aria-pressed="'+(ui.stockFilter===v)+'"')).join('')+'</div><div class="food-stock-list">'+(lots.length?lots.map(l=>'<article class="food-panel food-stock-card"><details><summary><span class="food-stock-symbol" aria-hidden="true">'+foodIcon('stock')+'</span><span class="food-stock-name"><strong>'+esc(l.name)+'</strong><small>'+l.remaining+' '+esc(l.unit)+' · '+esc(l.location)+' · '+(l.kind==='cooked'?'熟食':F.category(l)==='seasoning'?'调味品':'原材料')+'</small></span>'+exp(l)+'</summary><div class="food-stock-info"><dl><div><dt>'+(l.kind==='cooked'?'制作日期':'生产日期')+'</dt><dd>'+esc(l.producedOn||'未记录')+'</dd></div><div><dt>保质期</dt><dd>'+(l.shelfLife?l.shelfLife+({days:'天',weeks:'周',months:'个月',years:'年'}[l.shelfLifeUnit]||'天'):'未记录')+'</dd></div><div><dt>到期日</dt><dd>'+esc(l.expires||'未设置')+'</dd></div></dl><div class="food-row">'+(l.parentMealId?btn('查看这次做菜','open-meal','data-id="'+esc(l.parentMealId)+'"'):btn('盘点 / 编辑','stock-edit','data-id="'+esc(l.id)+'"'))+(l.kind==='cooked'&&(!l.expires||l.expires>=F.today())?btn('安排吃掉','choose-left','data-id="'+esc(l.id)+'"'):'')+btn(l.parentMealId?'丢弃剩菜':'丢弃 / 删除','delete','data-id="'+esc(l.id)+'"')+'</div></div></details></article>').join(''):empty('这里还没有库存。记录第一批食物，开始管理保质期。'))+'</div></section></div>';}
function planPage(){const start=startOfWeek(ui.date),ms=F.meals(state()),m=selected();return '<div class="food-heading"><div><h1>安排三餐</h1><small>'+start+' — '+F.addDays(start,6)+'</small></div><div class="food-row">'+btn('上一周','week','data-delta="-7"')+btn('今天','today')+btn('下一周','week','data-delta="7"')+'</div></div><div class="food-row food-margin">'+btn('按冰箱随机填空','random','',true)+'<small>已有安排与锁定餐次保留，只从你的菜谱和剩菜里挑。</small></div>'+(ui.random?'<section class="food-panel food-margin">'+header('安排草案')+(ui.random.length?ui.random.map(p=>'<p>'+p.date+' '+F.SLOTS[p.slot]+' · '+esc(p.name)+'</p>').join(''):empty('没有足够食材可继续安排。先入库或补全菜谱用量。'))+'<div class="food-row">'+btn('换一批','random')+btn('采用安排','adopt','',true)+btn('收起','close-random')+'</div></section>':'')+dayPicker(start)+'<div class="food-plan-workspace"><div class="food-week">'+Array.from({length:7},(_,i)=>{const date=F.addDays(start,i);return '<div><h3>'+['一','二','三','四','五','六','日'][i]+' <small>'+date.slice(5)+'</small></h3>'+F.SLOTS.map((n,slot)=>{const v=ms.find(x=>x.date===date&&x.slot===slot);return btn('<small>'+n+(v?.locked?' · 锁定':'')+'</small><span>'+esc(v?.snapshot.name||'＋ 安排')+'</span>','plan-select','data-date="'+date+'" data-slot="'+slot+'" aria-pressed="'+(ui.date===date&&ui.slot===slot)+'"');}).join('')+'</div>';}).join('')+'</div><section class="food-panel food-plan-detail">'+header(ui.date+' '+F.SLOTS[ui.slot])+(m?'<label class="food-check"><input type="checkbox" data-food-change="lock" '+(m.locked?'checked':'')+'>锁定这餐</label>'+mealDetail(m)+(!m.cookedAt?btn('取消这餐','delete','data-id="'+esc(m.id)+'"'):''):btn('选择菜谱或剩菜','choose','',true))+'</section></div>';}
function shopPanel(compact=false){const start=startOfWeek(ui.date),items=F.shopping(state(),start,F.addDays(start,6)),manual=F.list(state(),'shopping').filter(x=>!x.bought);let rows=[...items.map(x=>({...x,key:F.nameKey(x.name)+'|'+x.unit})),...manual];const count=rows.length;if(compact)rows=rows.slice(0,4);return '<section class="food-panel food-shop">'+header('采购清单',compact?btn('全部采购','tab','data-tab="shop"'):'<small>'+count+' 项待买</small>')+(compact?'':'<p class="food-muted">'+start+' 起的一周 · 已减去可用库存</p>')+(rows.length?rows.map((x,i)=>{const key=x.id||x.key,d=ui.purchaseDrafts[key]||{};return '<details class="food-purchase-item"><summary><span class="food-purchase-check" aria-hidden="true"></span><strong>'+esc(x.name)+'</strong><small>'+x.quantity+' '+esc(x.unit)+'</small><span aria-hidden="true">›</span></summary><form data-food-form="purchase" class="food-purchase" data-index="'+i+'" data-key="'+esc(key)+'">'+field('实际购买量 · '+x.unit,'quantity',d.quantity??x.quantity,'number','min="0.001" step="any" inputmode="decimal"')+lifeForm(d)+'<button type="submit" class="food-btn food-primary">已买，放入库存</button></form></details>';}).join(''):empty('要买的都齐了，安心做饭。'))+(compact?(count>4?btn('查看其余 '+(count-4)+' 项','tab','data-tab="shop"'):''):'<form data-food-form="shopping-add" class="food-inline"><h3>再买点什么</h3>'+field('食物与数量','line','','text','placeholder="例如：牛奶500ml" required')+'<button class="food-btn" type="submit">加入采购</button></form>')+'</section>';}

function lifeForm(d={},cooked=false){
const legacy=d.expires&&!d.producedOn&&!d.shelfLife;
return '<fieldset class="food-life"><legend>'+(cooked?'保存期限':'生产日期与保质期')+'</legend><div class="food-life-grid">'+field(cooked?'制作日期':'生产日期','producedOn',d.producedOn||'','date')+'<div class="food-field"><label>保质期时长</label><div class="food-duration"><input aria-label="保质期时长" name="shelfLife" type="number" inputmode="numeric" min="1" step="1" value="'+esc(d.shelfLife??'')+'" placeholder="如 12"><select aria-label="保质期单位" name="shelfLifeUnit">'+[['days','天'],['weeks','周'],['months','个月'],['years','年']].map(([v,n])=>'<option value="'+v+'" '+((d.shelfLifeUnit||'days')===v?'selected':'')+'>'+n+'</option>').join('')+'</select></div></div></div><output class="food-life-preview" aria-live="polite">'+lifePreview(d)+'</output><details class="food-life-legacy" '+(legacy?'open':'')+'><summary>仅知道到期日</summary>'+field('直接填写到期日','expires',legacy?d.expires:'','date')+'<small>填写生产日期与时长后，优先按上方计算。</small></details><small>'+(cooked?'按你确认的保存时长填写。':'按包装填写；散装食材不知道期限可暂时留空。')+'</small></fieldset>';
}
function lifePreview(d){try{const l=F.lifeFields(d);return l.expires?'到期日 <strong>'+esc(l.expires)+'</strong><span>'+esc(F.expiryLabel(l.expires))+'</span>':'填写日期和时长，自动计算到期日';}catch(e){return esc(e.message);}}
function refreshLife(form){const el=form?.querySelector('.food-life-preview');if(el)el.innerHTML=lifePreview(Object.fromEntries(new FormData(form)));}
function foodIcon(kind){const paths=kind==='recipe'?'<path d="M6 4h12v17H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm0 0v13m-2 2c0-1 1-2 2-2h12M9 8h6m-6 4h4"/>':'<path d="M5 5h14v16H5zM4 2h16v3H4m1 7h14m-4-4v2m0 5v2"/>';return '<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths+'</svg>';}
function recipeDetails(){const r=F.get(state(),ui.recipeView);if(!r)return recipeList();return '<section class="food-panel food-recipe-reader"><div class="food-heading">'+btn('‹ 菜谱列表','recipe-back')+btn('编辑','recipe-edit','data-id="'+esc(r.id)+'"')+'</div><small class="food-eyebrow">我的菜谱</small><h1>'+esc(r.name)+'</h1><p class="food-muted">'+kcal(r.kcal)+' · '+r.ingredients.length+' 种用料 · '+r.steps.length+' 步</p><h2>准备材料</h2>'+ingredientGroups(r.ingredients)+'<h2>开始做菜</h2><ol class="food-directions">'+r.steps.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol><div class="food-row">'+btn('安排到一餐','choose-recipe','data-id="'+esc(r.id)+'"',true)+btn('删除菜谱','delete','data-id="'+esc(r.id)+'"')+'</div></section>';}
function dayPicker(start){const ms=F.meals(state());return '<div class="food-mobile-plan"><div class="food-day-strip">'+Array.from({length:7},(_,i)=>{const d=F.addDays(start,i);return btn('<small>'+['一','二','三','四','五','六','日'][i]+'</small><strong>'+Number(d.slice(8))+'</strong><i class="'+(ms.some(m=>m.date===d)?'has-meal':'')+'"></i>','day-select','data-date="'+d+'" aria-pressed="'+(ui.date===d)+'"');}).join('')+'</div><div class="food-day-meals">'+F.SLOTS.map((n,slot)=>{const m=ms.find(x=>x.date===ui.date&&x.slot===slot);return btn('<small>'+n+'</small><span>'+esc(m?.snapshot.name||'添加这一餐')+'</span><small>'+(m?.finishedAt?'已吃':m?kcal(m.snapshot.kcal):'＋')+'</small>','plan-select','data-date="'+ui.date+'" data-slot="'+slot+'" aria-pressed="'+(ui.slot===slot)+'"');}).join('')+'</div></div>';}
function render(){if(!host||!ctx.getState())return;const key=ui.tab+':'+(ui.editor||'')+':'+(ui.recipeView||'');const oldScroll=host.querySelector('.food-content')?.scrollTop||0;const outerScroll=host.parentElement?.scrollTop||0;const same=host.dataset.viewKey===key;host.dataset.viewKey=key;host.innerHTML='<nav class="food-tabs" aria-label="饮食模块">'+[['overview','概览'],['recipes','菜谱'],['stock','库存'],['plan','排餐'],['shop','采购']].map(([id,n])=>btn(n,'tab','data-tab="'+id+'" aria-current="'+(ui.tab===id?'page':'false')+'"')).join('')+'</nav><div class="food-content">'+(ui.editor==='choose'?(ui.recipeView?recipeDetails():recipeList(true)):ui.tab==='overview'?overview():ui.tab==='recipes'?recipesPage():ui.tab==='stock'?stockPage():ui.tab==='plan'?planPage():shopPanel())+(ui.confirm?'<div class="food-panel food-confirm"><p>确认移除这条记录？已有摄入历史会保留。</p><div class="food-row">'+btn('确认移除','confirm-delete','data-id="'+esc(ui.confirm)+'"')+btn('取消','cancel-delete')+'</div></div>':'')+'</div><div class="food-status" role="status" aria-live="polite">'+esc(ui.message)+'</div>';host.querySelector('.food-content').scrollTop=same?oldScroll:0;if(host.parentElement)host.parentElement.scrollTop=same?outerScroll:0;try{localStorage.setItem('psfocus_food_ui',JSON.stringify({tab:ui.tab}));}catch(_){} }


function draftFromForm(){const f=host.querySelector('form[data-food-form="recipe"]');if(f)ui.recipeDraft={...ui.recipeDraft,...Object.fromEntries(new FormData(f))};}
async function importLink(){draftFromForm();const match=String(ui.recipeDraft.sourceUrl||'').match(/https?:\/\/[^\s<>"“”]+/);if(!match)throw Error('请粘贴包含网址的分享文本');ui.recipeDraft.sourceUrl=match[0];ui.busy=true;render();try{const res=await ctx.importRecipe({action:'recipeLink',url:match[0]});if(res.code||!res.text)throw Error(res.msg||'没有读到完整菜谱，请粘贴正文或导入截图');ui.recipeDraft={...ui.recipeDraft,...F.parseRecipe(res.text),categories:Object.fromEntries(F.parseRecipe(res.text).ingredients.map(i=>[F.nameKey(i.name),F.category(i)])),sourceUrl:match[0]};ui.message='已读取来源，请核对材料、步骤和份量后保存。';}finally{ui.busy=false;render();}}
async function importImage(file){if(!file)return;draftFromForm();ui.busy=true;render();try{const encoded=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const scale=Math.min(1,1600/Math.max(im.width,im.height)),canvas=document.createElement('canvas');canvas.width=Math.round(im.width*scale);canvas.height=Math.round(im.height*scale);canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.85).split(',')[1]);};im.onerror=()=>reject(Error('无法读取这张图片'));im.src=r.result;};r.onerror=()=>reject(Error('图片读取失败'));r.readAsDataURL(file);});const res=await ctx.importRecipe({imageBase64:encoded,mode:'printed'});if(res.code||!res.text)throw Error(res.msg||'没有识别到文字，可改用粘贴文字或手动填写');ui.recipeDraft={...ui.recipeDraft,...F.parseRecipe(res.text),categories:Object.fromEntries(F.parseRecipe(res.text).ingredients.map(i=>[F.nameKey(i.name),F.category(i)]))};ui.message='识别完成，请核对文字和用量；整道菜热量可自行补充。';}finally{ui.busy=false;render();}}
function refreshClassification(){const el=host.querySelector('.food-classification');if(el)el.innerHTML=classificationPreview();}
function captureForm(form){if(!form)return;const d=Object.fromEntries(new FormData(form));if(form.dataset.foodForm==='recipe')ui.recipeDraft={...ui.recipeDraft,...d};if(form.dataset.foodForm==='stock')ui.stockDraft={...ui.stockDraft,...d,...(Object.hasOwn(d,'quantity')?{remaining:d.quantity}:{})};if(form.dataset.foodForm==='purchase')ui.purchaseDrafts[form.dataset.key]=d;if(form.dataset.foodForm==='leftover')ui.leftoverDraft={...ui.leftoverDraft,...d};}
function focusEditor(){host.querySelector('.food-editor-pane [name=name]')?.focus();}
function bind(){
host.addEventListener('input',e=>{captureForm(e.target.closest('form'));refreshLife(e.target.closest('form'));if(e.target.id==='food-search'){ui.query=e.target.value;if(e.isComposing)return;const caret=e.target.selectionStart;render();const q=host.querySelector('#food-search');q?.focus();q?.setSelectionRange(caret,caret);}if(e.target.name==='ingredients'&&!e.isComposing)refreshClassification();});
host.addEventListener('compositionend',e=>{captureForm(e.target.closest('form'));if(e.target.id==='food-search'){ui.query=e.target.value;render();host.querySelector('#food-search')?.focus();}if(e.target.name==='ingredients')refreshClassification();});
host.addEventListener('change',async e=>{captureForm(e.target.closest('form'));refreshLife(e.target.closest('form'));try{if(e.target.matches('[data-food-image]'))return await importImage(e.target.files[0]);if(e.target.dataset.foodChange==='lock'){const m=selected();if(m)commit(s=>F.put(s,{...F.get(s,m.id),locked:e.target.checked}),'已保存锁定状态');}if(e.target.dataset.foodChange==='scale'){const m=selected();if(m)commit(s=>F.plan(s,{...m,scale:Number(e.target.value)}),'用量与采购已更新');}}catch(err){notify(err.message,true);}});
host.addEventListener('click',async e=>{const el=e.target.closest('[data-food-action]');if(!el||el.disabled)return;e.preventDefault();const a=el.dataset.foodAction;try{
if(a==='tab'){ui.message='';ui.recipeView=null;ui.tab=el.dataset.tab;ui.editor=null;ui.confirm=null;if(ui.tab==='overview')ui.date=F.today();render();}
else if(a==='meal-select'||a==='plan-select'){ui.slot=+el.dataset.slot;ui.date=el.dataset.date||F.today();ui.editor=null;ui.mealExpanded=true;render();}
else if(a==='recipe-view'){ui.recipeView=el.dataset.id;render();}
else if(a==='recipe-back'){ui.recipeView=null;render();}
else if(a==='day-select'){ui.date=el.dataset.date;ui.editor=null;render();}
else if(a==='recipe-new'){ui.message='';ui.recipeView=null;ui.tab='recipes';ui.editor='recipe';if(ui.recipeDraft.id)ui.recipeDraft={};render();focusEditor();}
else if(a==='recipe-edit'){ui.recipeView=null;ui.tab='recipes';ui.editor='recipe';const r=F.get(state(),el.dataset.id);ui.recipeDraft={...r,categories:Object.fromEntries((r.ingredients||[]).map(i=>[F.nameKey(i.name),F.category(i)])),mealType:r.mealTypes?.length===1?r.mealTypes[0]:'all'};render();focusEditor();}
else if(a==='ingredient-category'){const name=el.dataset.name,item=recipeItems().find(i=>F.nameKey(i.name)===name);if(item){ui.recipeDraft.categories={...ui.recipeDraft.categories,[name]:F.category(item)==='seasoning'?'ingredient':'seasoning'};refreshClassification();}}
else if(a==='close-editor'){ui.editor=null;render();}
else if(a==='parse-text'){draftFromForm();const parsed=F.parseRecipe(ui.recipeDraft.sourceText);ui.recipeDraft={...ui.recipeDraft,...parsed,categories:Object.fromEntries(parsed.ingredients.map(i=>[F.nameKey(i.name),F.category(i)]))};render();}
else if(a==='read-link'){await importLink();}
else if(a==='choose'){ui.editor='choose';ui.query='';render();}
else if(a==='choose-recipe'||a==='choose-left'){const id=el.dataset.id;commit(s=>F.plan(s,{date:ui.date,slot:ui.slot,...(a==='choose-left'?{sourceLotId:id}:{recipeId:id})}),'已安排；实际库存尚未扣减');ui.editor=null;if(ui.tab==='recipes'||ui.tab==='stock')ui.tab='plan';render();}
else if(a==='cook'){const ok=!!host.querySelector('#food-confirm-unknown')?.checked;commit(s=>F.cook(s,el.dataset.id,ok),'已做好，原料只扣一次；吃完后再记录剩余');}
else if(a==='finish'){const ok=!!host.querySelector('#food-confirm-unknown')?.checked;commit(s=>F.finish(s,el.dataset.id,0,'',ok),'已记录吃完，摄入与库存已更新');}
else if(a==='leftover'){ui.editor='leftover';ui.leftoverDraft={left:50,producedOn:F.today(),shelfLife:'',confirmedUnknown:!!host.querySelector('#food-confirm-unknown')?.checked};render();}
else if(a==='left-choice'){ui.leftoverDraft.left=Math.round(+el.dataset.left*100);const i=host.querySelector('[name=left]');if(i)i.value=ui.leftoverDraft.left;}
else if(a==='undo-meal'){commit(s=>F.undoMeal(s,el.dataset.id),'已撤销这次制作与摄入记录');}
else if(a==='stock-new'){ui.message='';ui.tab='stock';ui.editor='stock';if(ui.stockDraft.id)ui.stockDraft={};render();focusEditor();}
else if(a==='stock-edit'){ui.tab='stock';ui.editor='stock';ui.stockDraft={...F.stock(state()).find(l=>l.id===el.dataset.id)};render();focusEditor();}
else if(a==='stock-soon'){ui.tab='stock';ui.editor=null;ui.stockFilter='soon';render();}
else if(a==='stock-filter'){ui.stockFilter=el.dataset.filter;render();}
else if(a==='week'){ui.date=F.addDays(ui.date,+el.dataset.delta);ui.random=null;render();}
else if(a==='today'){ui.date=F.today();render();}
else if(a==='random'){ui.random=F.randomDraft(state(),startOfWeek(ui.date));render();}
else if(a==='adopt'){commit(s=>F.applyDraft(s,ui.random||[]),'已采用可用的空餐次安排');ui.random=null;render();}
else if(a==='close-random'){ui.random=null;render();}
else if(a==='delete'){ui.confirm=el.dataset.id;render();host.querySelector('.food-confirm')?.scrollIntoView({block:'nearest'});}
else if(a==='cancel-delete'){ui.confirm=null;render();}
else if(a==='confirm-delete'){commit(s=>{const id=el.dataset.id;if(id.startsWith('left:')){const m=F.get(s,id.slice(5));if(m)F.put(s,{...m,leftDiscarded:true});}else F.remove(s,id);},'已移除');ui.confirm=null;ui.recipeView=null;render();}
else if(a==='open-meal'){const m=F.meals(state()).find(x=>x.id===el.dataset.id);if(m){ui.date=m.date;ui.slot=m.slot;ui.tab='plan';ui.editor=null;render();}}
else if(a==='calendar'){ctx.openCalendar(el.dataset.date);}
}catch(err){notify(err.message,true);}});
host.addEventListener('submit',e=>{const form=e.target.closest('[data-food-form]');if(!form)return;e.preventDefault();captureForm(form);const d=Object.fromEntries(new FormData(form)),type=form.dataset.foodForm;try{
if(type==='recipe'){commit(s=>F.saveRecipe(s,{...ui.recipeDraft,...d,ingredients:recipeItems(),mealTypes:d.mealType==='all'?[]:[+d.mealType]}),'菜谱已保存，可继续录入');ui.recipeDraft={};ui.editor=null;render();}
else if(type==='stock'){const cat=d.stockClass==='seasoning'?'seasoning':d.stockClass==='ingredient'?'ingredient':undefined;const kind=d.stockClass==='cooked'?'cooked':'raw';
if(d.batch?.trim()){const rows=F.ingredients(d.batch);if(rows.some(i=>i.quantity==null||i.quantity<=0))throw Error('批量入库每行需要明确数量，例如“生抽500ml”');const life=F.lifeFields(d);commit(s=>rows.forEach(i=>F.addLot(s,{...i,category:cat||F.category(i),kind,...life,location:d.location})),'已逐项分类并入库');}
else if(ui.stockDraft.id){const l=F.get(state(),ui.stockDraft.id),current=F.stock(state()).find(x=>x.id===l.id)?.remaining||0;const n=Number(d.quantity);if(d.quantity===''||!Number.isFinite(n)||n<0)throw Error('请输入有效现有数量');const life=F.lifeFields(d);commit(s=>F.put(s,{...l,name:d.name||l.name,category:cat||F.category(d.name||l.name),quantity:F.round(l.quantity-current+n),...life,location:d.location||l.location}),'库存分类与数量已更新');}
else commit(s=>F.addLot(s,{...d,kind,category:cat}),'已入库');ui.editor=null;ui.stockDraft={};render();}
else if(type==='leftover'){const m=selected(),ok=ui.leftoverDraft.confirmedUnknown||!!host.querySelector('#food-confirm-unknown')?.checked;commit(s=>F.finish(s,m.id,Number(d.left)/100,d,ok),'已记录吃掉的部分，剩菜已留在冰箱');ui.editor=null;ui.leftoverDraft={};render();}
else if(type==='shopping-add'){const i=F.ingredient(d.line);if(!i||i.quantity==null)throw Error('请输入食物、数量与单位');commit(s=>F.put(s,{...i,category:F.category(i),type:'shopping',bought:false}),'已加入采购');}
else if(type==='purchase'){const start=startOfWeek(ui.date),auto=F.shopping(state(),start,F.addDays(start,6)),manual=F.list(state(),'shopping').filter(x=>!x.bought);const item=[...auto.map(x=>({...x,key:F.nameKey(x.name)+'|'+x.unit})),...manual].find(x=>(x.id||x.key)===form.dataset.key);if(!item)throw Error('这项采购已经处理，请查看最新清单');commit(s=>{F.addLot(s,{name:item.name,quantity:d.quantity,unit:item.unit,category:F.category(item),...F.lifeFields(d)});if(item.id)F.put(s,{...item,bought:true});delete ui.purchaseDrafts[form.dataset.key];},'已按实买量分类入库，缺料已重算');}
}catch(err){notify(err.message,true);}});
}
window.PSFoodUI={prepareReload(){if(host?.isConnected){host.querySelectorAll('form').forEach(captureForm);}try{sessionStorage.setItem('psfocus_food_reload_draft',JSON.stringify({...ui,busy:false,confirm:null}));}catch(_){}},mount(root,context){ctx=context;if(!root.querySelector('.ps-food')){root.innerHTML='<div class="ps-food'+(document.body.classList.contains('section-food')?'':' food-mobile')+'"></div>';host=root.querySelector('.ps-food');bind();}else host=root.querySelector('.ps-food');if(host.contains(document.activeElement)&&document.activeElement.matches('input,textarea,select'))return;render();},openMeal(id){const m=F.meals(state()).find(x=>x.id===id);if(m){ui.date=m.date;ui.slot=m.slot;ui.tab='plan';ui.editor=null;}},render};
})();
