(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PSFood=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DAY=86400000,SLOTS=['早餐','午餐','晚餐'];
const copy=x=>JSON.parse(JSON.stringify(x));
const round=x=>Math.round((Number(x)||0)*1000)/1000;
const dateKey=d=>{d=d instanceof Date?d:new Date(d===undefined?Date.now():d);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const addDays=(day,n)=>dateKey(new Date(day+'T12:00:00').getTime()+n*DAY);
const today=()=>dateKey();
const uid=()=> 'food:'+((typeof crypto!=='undefined'&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));
const validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(d||'')&&dateKey(new Date(d+'T12:00:00'))===d;
const num=(v,label,allowZero=false)=>{const n=Number(v);if(v===''||v==null||!Number.isFinite(n)||(allowZero?n<0:n<=0))throw Error(label+'需要填写有效数量');return n};
const nameKey=s=>String(s||'').trim().replace(/西红柿/g,'番茄').replace(/土豆/g,'马铃薯').replace(/\s+/g,'').toLowerCase();
function unit(q,u){u=String(u||'').trim().toLowerCase();const units={'克':['g',1],'g':['g',1],'千克':['g',1000],'公斤':['g',1000],'kg':['g',1000],'斤':['g',500],'毫升':['ml',1],'ml':['ml',1],'升':['ml',1000],'l':['ml',1000],'个':['个',1],'枚':['个',1],'份':['份',1],'包':['包',1],'盒':['盒',1],'勺':['勺',1]};const v=units[u];return {quantity:q==null?null:round(q*(v?v[1]:1)),unit:v?v[0]:u||'待核对'};}
function ingredient(line){line=String(line||'').trim().replace(/^[-•·]\s*/,'');if(!line)return null;const m=line.match(/^(.+?)\s*[:：]?\s*(\d+(?:\.\d+)?)\s*(kg|ml|g|l|千克|公斤|毫升|克|斤|升|个|枚|份|包|盒|勺)\s*(.*)$/i);if(!m)return {name:line.replace(/\s*(适量|少许)$/,''),quantity:null,unit:'适量',note:line,optional:false};return {name:m[1].trim(),...unit(+m[2],m[3]),note:m[4],optional:false};}
const ingredients=text=>String(text||'').split(/[\n，,；;]+/).map(ingredient).filter(Boolean);
function parseRecipe(text){const lines=String(text||'').trim().split(/\n+/).map(s=>s.trim()).filter(Boolean);let title=lines.shift()||'',section='ingredients',ing=[],steps=[];for(const line of lines){if(/^(食材|用料|材料)\s*[:：]?$/.test(line)){section='ingredients';continue}if(/^(步骤|做法|制作方法)\s*[:：]?$/.test(line)){section='steps';continue}if(section==='steps'||/^\d+[.、．)）]/.test(line)){section='steps';steps.push(line.replace(/^\d+[.、．)）]\s*/,''));}else ing.push(...ingredients(line));}return {name:title.slice(0,120),ingredients:ing,steps,kcal:null,sourceText:text};}
function entries(s){return Array.isArray(s.foodEntries)?s.foodEntries:[]}
const list=(s,type)=>entries(s).filter(x=>x&&x.type===type&&!x.deleted);
const get=(s,id)=>entries(s).find(x=>x.id===id&&!x.deleted);
function put(s,item){if(!Array.isArray(s.foodEntries))s.foodEntries=[];const i=s.foodEntries.findIndex(x=>x.id===item.id),old=i<0?null:s.foodEntries[i];const ts=Math.max(Date.now(),(+s._cloudUpdatedAt||0)+1,(+old?.updatedAt||0)+1);const value={...item,id:item.id||uid(),createdAt:old?.createdAt||item.createdAt||ts,updatedAt:ts};if(i<0)s.foodEntries.push(value);else s.foodEntries[i]=value;return value;}
function merge(a,b){const out=new Map();for(const x of [...(Array.isArray(a)?a:[]),...(Array.isArray(b)?b:[])]){if(!x?.id)continue;const old=out.get(x.id);if(!old||(+x.updatedAt||0)>(+old.updatedAt||0)||((+x.updatedAt||0)===(+old.updatedAt||0)&&JSON.stringify(x)>JSON.stringify(old)))out.set(x.id,copy(x));}return [...out.values()];}
function preserve(target,local){if(target&&local&&(target.foodEntries||local.foodEntries))target.foodEntries=merge(target.foodEntries,local.foodEntries);return target;}
function saveRecipe(s,input){if(!String(input.name||'').trim())throw Error('请填写菜名');const items=typeof input.ingredients==='string'?ingredients(input.ingredients):copy(input.ingredients||[]);if(!items.length&&!input.sourceUrl&&!input.sourceText)throw Error('请填写材料，或保留来源作为待整理菜谱');for(const i of items){if(!i.name)throw Error('材料名称不能为空');if(i.quantity!=null)num(i.quantity,'材料用量');}return put(s,{...input,type:'recipe',name:input.name.trim(),ingredients:items,steps:Array.isArray(input.steps)?input.steps:String(input.steps||'').split('\n').filter(Boolean),kcal:input.kcal===''||input.kcal==null?null:num(input.kcal,'整道菜热量',true)});}
function addLot(s,input){if(!String(input.name||'').trim())throw Error('请填写食物名称');if(input.expires&&!validDate(input.expires))throw Error('请填写有效的到期日期');const u=unit(num(input.quantity,'入库量'),input.unit);return put(s,{...input,type:'lot',name:input.name.trim(),...u,kind:input.kind==='cooked'?'cooked':'raw',expires:input.expires||'',location:input.location||'冷藏',kcal:input.kcal===''||input.kcal==null?null:num(input.kcal,'这批熟食总热量',true)});}
function mealDate(s,m){const ev=(s.events||[]).find(e=>e.foodMealId===m.id);const t=ev?.schedules?.[0]?.start||ev?.start;return t?dateKey(t):m.date;}
function meals(s){return list(s,'meal').map(m=>({...m,date:mealDate(s,m)})).sort((a,b)=>a.date.localeCompare(b.date)||a.slot-b.slot);}
function mirrorCalendar(s,m){if(!Array.isArray(s.events))s.events=[];const id='event:'+m.id;const old=s.events.find(e=>e.id===id);if(m.deleted){s.events=s.events.filter(e=>e.id!==id);return;}const start=new Date(m.date+'T'+['08','12','18'][m.slot]+':00:00').getTime(),end=start+30*60000;const event={...old,id,foodMealId:m.id,title:SLOTS[m.slot]+' · '+m.snapshot.name,start,end,allDay:false,projectId:null,tags:['饮食'],createdAt:old?.createdAt||m.createdAt,updatedAt:m.updatedAt,schedules:[{id:'schedule:'+m.id,kind:'range',start,end,allDay:false,repeat:'none'}]};const i=s.events.findIndex(e=>e.id===id);if(i<0)s.events.push(event);else s.events[i]=event;}
function plan(s,{date,slot,recipeId,sourceLotId,scale=1,amount,id,auto=false}){if(!validDate(date)||![0,1,2].includes(+slot))throw Error('请选择日期和餐次');const old=id?get(s,id):meals(s).find(m=>m.date===date&&m.slot===+slot);if(old?.cookedAt||old?.finishedAt)throw Error('这餐已开始制作，请先撤销完成记录');let snapshot;if(sourceLotId){const lot=stock(s).find(x=>x.id===sourceLotId);if(!lot)throw Error('剩菜已用完或不存在');if(lot.expires&&lot.expires<date)throw Error('这批食物会在该餐之前到期');amount=num(amount==null?lot.remaining:amount,'取用量');if(amount>lot.remaining+1e-6)throw Error('取用量超过剩余量');snapshot={name:lot.name,ingredients:[],steps:['取用冰箱中已做好的食物。'],kcal:lot.kcal==null?null:round(lot.kcal/lot.quantity*amount)};}else{const r=get(s,recipeId);if(!r||r.type!=='recipe')throw Error('请选择已有菜谱');scale=num(scale,'这次做多少');snapshot=copy(r);}
const m=put(s,{id:old?.id||id||(get(s,'food:meal:'+date+':'+slot)?uid():('food:meal:'+date+':'+slot)),type:'meal',date,slot:+slot,recipeId:recipeId||null,sourceLotId:sourceLotId||null,amount:amount||null,scale:sourceLotId?1:scale,snapshot,locked:old?.locked||false,auto,cookedAt:null,finishedAt:null,eatenFraction:null,allocations:[]});mirrorCalendar(s,m);return m;}
function stock(s){const ms=meals(s);const used=new Map();for(const m of ms){if(!m.cookedAt)continue;for(const a of m.allocations||[])used.set(a.lotId,round((used.get(a.lotId)||0)+a.quantity));}const lots=list(s,'lot').map(l=>({...l,remaining:round(l.quantity-(used.get(l.id)||0))}));for(const m of ms){if(m.sourceLotId||!m.finishedAt||m.eatenFraction>=1)continue;const quantity=round(1-m.eatenFraction);lots.push({id:'left:'+m.id,type:'lot',kind:'cooked',name:m.snapshot.name+'（剩菜）',unit:'份',quantity,remaining:m.leftDiscarded?0:round(quantity-(used.get('left:'+m.id)||0)),expires:m.leftoverExpires||'',location:'冷藏',kcal:m.snapshot.kcal==null?null:round(m.snapshot.kcal*m.scale*quantity),parentMealId:m.id,createdAt:m.finishedAt});}return lots.filter(l=>l.remaining>1e-6).sort((a,b)=>(a.expires||'9999').localeCompare(b.expires||'9999')||a.createdAt-b.createdAt);}
function requirements(m){return (m.snapshot.ingredients||[]).filter(i=>!i.optional).map(i=>({...i,...unit(i.quantity==null?null:i.quantity*m.scale,i.unit)}));}
function allocate(pool,m){const date=m.date,allocations=[],missing=[],unknown=[];if(m.sourceLotId){const l=pool.find(x=>x.id===m.sourceLotId&&(!x.expires||x.expires>=date));const q=m.amount;if(l&&l.remaining+1e-6>=q){l.remaining=round(l.remaining-q);allocations.push({lotId:l.id,quantity:q});}else missing.push({name:m.snapshot.name,quantity:round(q-(l?.remaining||0)),unit:l?.unit||'份',sourceLotId:m.sourceLotId});return {allocations,missing,unknown};}
for(const i of requirements(m)){if(i.quantity==null){unknown.push(i);continue;}let remaining=i.quantity;for(const l of pool){if(l.kind!=='raw'||nameKey(l.name)!==nameKey(i.name)||l.unit!==i.unit||(l.expires&&l.expires<date))continue;const q=Math.min(Math.max(0,l.remaining),remaining);if(q>0){l.remaining=round(l.remaining-q);remaining=round(remaining-q);allocations.push({lotId:l.id,quantity:q});}if(remaining<=0)break;}if(remaining>0)missing.push({...i,quantity:remaining});}return {allocations,missing,unknown};}
function projection(s){const pool=copy(stock(s)),byMeal={};for(const m of meals(s).filter(m=>!m.cookedAt&&!m.finishedAt))byMeal[m.id]=allocate(pool,m);return {pool,byMeal};}
function shopping(s,start,end){const projected=projection(s),map=new Map();for(const m of meals(s)){if(m.date<start||m.date>end||m.cookedAt||m.finishedAt)continue;for(const i of projected.byMeal[m.id]?.missing||[]){if(i.sourceLotId)continue;const key=nameKey(i.name)+'|'+i.unit;const r=map.get(key)||{name:i.name,quantity:0,unit:i.unit,meals:[]};r.quantity=round(r.quantity+i.quantity);r.meals.push(m.date+' '+SLOTS[m.slot]);map.set(key,r);}}return [...map.values()];}
function cook(s,id,confirmUnknown=false){const m=get(s,id);if(!m||m.type!=='meal')throw Error('这餐不存在');if(m.cookedAt)return m;if(m.sourceLotId)throw Error('现成剩菜直接记录吃完或剩下多少即可');const p=projection(s).byMeal[id];if(!p||p.missing.length)throw Error('材料不足，请先补记入库或调整菜谱');if(p.unknown.length&&!confirmUnknown)throw Error('存在“适量”或未换算材料，请核对后勾选确认');const available=stock(s);if(p.allocations.some(a=>{const l=available.find(x=>x.id===a.lotId);return !l||(l.expires&&l.expires<today())||l.remaining+1e-6<a.quantity}))throw Error('分配的材料已到期或数量改变，请先检查库存');return put(s,{...m,cookedAt:Date.now(),allocations:p.allocations});}
function finish(s,id,leftFraction,expires,confirmUnknown=false){let m=get(s,id);if(!m)throw Error('这餐不存在');if(m.finishedAt)return m;const left=Number(leftFraction);if(!Number.isFinite(left)||left<0||left>=1)throw Error('剩余比例应为0到不足100%');if(left>0&&!m.sourceLotId&&!validDate(expires))throw Error('有剩菜时，请填写计划吃完日期');if(m.sourceLotId){const pool=stock(s);const l=pool.find(x=>x.id===m.sourceLotId);const q=round(m.amount*(1-left));if(!l||l.remaining+1e-6<q||(l.expires&&l.expires<today()))throw Error('这批剩菜已用完或到期，请先核对库存');m=put(s,{...m,cookedAt:Date.now(),allocations:[{lotId:l.id,quantity:q}]});}else m=cook(s,id,confirmUnknown);return put(s,{...m,finishedAt:Date.now(),eatenFraction:1-left,leftoverExpires:left>0?expires:'',intakeDate:today()});}
function undoMeal(s,id){const m=get(s,id);if(!m)return;const linked=meals(s).filter(x=>x.sourceLotId==='left:'+id);if(linked.some(x=>x.cookedAt))throw Error('这餐的剩菜已经被吃过，请先撤销后续那一餐');for(const x of linked){const removed=put(s,{...x,deleted:true});mirrorCalendar(s,removed);}return put(s,{...m,cookedAt:null,finishedAt:null,eatenFraction:null,allocations:[],leftoverExpires:'',leftDiscarded:false});}
function remove(s,id){const item=get(s,id);if(!item)return;if(item.type==='meal'&&(item.cookedAt||item.finishedAt))throw Error('请先撤销这餐的完成记录');const r=put(s,{...item,deleted:true});if(item.type==='meal')mirrorCalendar(s,r);}
function nutrition(s,date){const plans=meals(s).filter(m=>m.date===date),eaten=meals(s).filter(m=>m.finishedAt&&m.intakeDate===date);const sum=(arr,actual)=>({kcal:round(arr.reduce((a,m)=>a+(m.snapshot.kcal==null?0:m.snapshot.kcal*m.scale*(actual?m.eatenFraction:1)),0)),unknown:arr.filter(m=>m.snapshot.kcal==null).length});return {planned:sum(plans,false),actual:sum(eaten,true)};}
function randomDraft(s,start,days=7){const draft=copy(s),result=[];for(let d=0;d<days;d++)for(let slot=0;slot<3;slot++){const date=addDays(start,d);if(date<today()||meals(draft).some(m=>m.date===date&&m.slot===slot))continue;const pool=projection(draft).pool;let options=[];for(const l of pool.filter(l=>l.kind==='cooked'&&l.remaining>0&&(!l.expires||l.expires>=date))){options.push({date,slot,sourceLotId:l.id,amount:l.remaining,name:l.name,urgency:l.expires||'9999',kind:0});}for(const r of list(draft,'recipe')){if(!r.ingredients?.length)continue;if(r.mealTypes?.length&&!r.mealTypes.includes(slot))continue;const candidate={date,slot,snapshot:r,scale:1},a=allocate(copy(pool),candidate);if(a.missing.length||a.unknown.length)continue;const expiry=a.allocations.map(x=>pool.find(l=>l.id===x.lotId)?.expires||'9999').sort()[0]||'9999';options.push({date,slot,recipeId:r.id,name:r.name,urgency:expiry,kind:1});}options.sort((a,b)=>a.urgency.localeCompare(b.urgency)||a.kind-b.kind);if(!options.length)continue;const top=options.filter(o=>o.urgency===options[0].urgency&&o.kind===options[0].kind);const chosen=top[Math.floor(Math.random()*top.length)];plan(draft,{...chosen,auto:true});result.push(chosen);}return result;}
function applyDraft(s,draft){const trial=copy(s);for(const p of draft){if(meals(trial).some(m=>m.date===p.date&&m.slot===p.slot))continue;const m=plan(trial,{...p,auto:true});const a=projection(trial).byMeal[m.id];if(a.missing.length||a.unknown.length)throw Error('库存或计划已变化，请重新生成安排');}s.foodEntries=trial.foodEntries;s.events=trial.events;}
function expiryLabel(expires){if(!expires)return '未设期限';const n=Math.round((new Date(expires+'T12:00:00')-new Date(today()+'T12:00:00'))/DAY);return n<0?'已过期'+(-n)+'天':n===0?'今天到期':n===1?'明天到期':'剩'+n+'天';}
return {SLOTS,dateKey,addDays,today,validDate,uid,round,nameKey,unit,ingredient,ingredients,parseRecipe,list,get,put,merge,preserve,saveRecipe,addLot,meals,mealDate,plan,stock,requirements,projection,shopping,cook,finish,undoMeal,remove,nutrition,randomDraft,applyDraft,expiryLabel};
});
